### ISSUE TITLE
Feedback (not working)

### ISSUE THREAD

**Issue by MythodeaLoL** [mervick/php-aaencoder#1]
Tested, not working.
Does not decode any of the code. =(

@mervick

**Comment by mervick** [comment]
I has made some changes. Try it now.
@FloridaStream

**Comment by mervick** [comment]
What version of php are you using?
It's required for PHP>=5.4

**Comment by MythodeaLoL** [comment]
php 5.6
testing this file https://openload.co/getdllink/pVL7g8Ybx9o

**Comment by mervick** [comment]
Now it works)

**Comment by MythodeaLoL** [comment]
Yes, good job man =) :+1:
