### ISSUE TITLE
problem with encode php7.2

### ISSUE THREAD

**Issue by Kabinjp** [mervick/php-aaencoder#4]
?��??= /����䣩? ~�ߩ��� //*��?��*/ ['_']; o=(???) =_=3; c=(?��?) =(???)-(???); (?��?) =(?��?)= (o^_^o)/ (o^_^o);(?��?)={?��?: '_' ,?��?? : ((?��??==3) +'_') [?��?] ,???? :(?��??+ '_')[o^_^o -(?��?)] ,?��??:((???==3) +'_')[???] }; (?��?) [?��?] =((?��??==3) +'_') [c^_^o];(?��?) ['c'] = ((?��?)+'_') [ (???)+(???)-(?��?) ];(?��?) ['o'] = ((?��?)+'_') [?��?];(?o?)=(?��?) ['c']+(?��?) ['o']+(?��?? +'_')[?��?]+ ((?��??==3) +'_') [???] + ((?��?) +'_') [(???)+(???)]+ ((???==3) +'_') [?��?]+((???==3) +'_') [(???) - (?��?)]+(?��?) ['c']+((?��?)+'_') [(???)+(???)]+ (?��?) ['o']+((???==3) +'_') [?��?];(?��?) ['_'] =(o^_^o) [?o?] [?o?];(?��?)=((???==3) +'_') [?��?]+ (?��?) .?��??+((?��?)+'_') [(???) + (???)]+((???==3) +'_') [o^_^o -?��?]+((???==3) +'_') [?��?]+ (?��?? +'_') [?��?]; (???)+=(?��?); (?��?)[?��?]='\\'; (?��?).?��??=(?��?+ ???)[o^_^o -(?��?)];(o???o)=(?��?? +'_')[c^_^o];(?��?) [?o?]='\"';(?��?) ['_'] ( (?��?) ['_'] (?��?+/*��?��*/(?��?)[?o?]+ (?��?)[?��?]+(?��?)+((???) + (?��?))+(c^_^o)+(?��?)[?��?]+(?��?)+(???)+((???) + (?��?))+(?��?)[?��?]+(?��?)+((???) + (?��?))+(???)+(?��?)[?��?]+(?��?)+((???) + (?��?))+(???)+(?��?)[?��?]+(?��?)+((???) + (?��?))+((???) + (o^_^o))+(?��?)[?o?]) (?��?)) ('_');

**Comment by mervick** [comment]
please provide your code and text for encrypt

**Comment by Kabinjp** [comment]
<?php
/**
 * Class AAEncoder
 * @author Andrey Izman <izmanw@gmail.com>
 * @link https://github.com/mervick/php-aaencoder
 * @license MIT
 */

/**
 * Class AAEncoder
 */
class AAEncoder
{
    /**
     * Encode any JavaScript program to Japanese style emoticons (^_^)
     * @param string $js
     * @param int $level [optional]
     * @return string
     */
    public static function encode($js, $level=0)
    {
        $result = "ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ ['_']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); " .
            "(ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);" .
            "(ﾟДﾟ)={ﾟΘﾟ: '_' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +'_') [ﾟΘﾟ] " .
            ",ﾟｰﾟﾉ :(ﾟωﾟﾉ+ '_')[o^_^o -(ﾟΘﾟ)] " .
            ",ﾟДﾟﾉ:((ﾟｰﾟ==3) +'_')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +'_') [c^_^o];" .
            "(ﾟДﾟ) ['c'] = ((ﾟДﾟ)+'_') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];" .
            "(ﾟДﾟ) ['o'] = ((ﾟДﾟ)+'_') [ﾟΘﾟ];" .
            "(ﾟoﾟ)=(ﾟДﾟ) ['c']+(ﾟДﾟ) ['o']+(ﾟωﾟﾉ +'_')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +'_') [ﾟｰﾟ] + " .
            "((ﾟДﾟ) +'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+" .
            "((ﾟｰﾟ==3) +'_') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) ['c']+" .
            "((ﾟДﾟ)+'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) ['o']+" .
            "((ﾟｰﾟ==3) +'_') [ﾟΘﾟ];(ﾟДﾟ) ['_'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];" .
            "(ﾟεﾟ)=((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+" .
            "((ﾟДﾟ)+'_') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +'_') [o^_^o -ﾟΘﾟ]+" .
            "((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟωﾟﾉ +'_') [ﾟΘﾟ]; " .
            "(ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]='\\\\'; " .
            "(ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];" .
            "(oﾟｰﾟo)=(ﾟωﾟﾉ +'_')[c^_^o];" .
            "(ﾟДﾟ) [ﾟoﾟ]='\\\"';" .
            "(ﾟДﾟ) ['_'] ( (ﾟДﾟ) ['_'] (ﾟεﾟ+" .
            "/*´∇｀*/(ﾟДﾟ)[ﾟoﾟ]+ ";

        for ($i = 0, $len = mb_strlen($js); $i < $len; $i++) {
            $code = unpack('N', mb_convert_encoding(mb_substr($js, $i, 1, 'UTF-8'), 'UCS-4BE', 'UTF-8'))[1];
            $text = '(ﾟДﾟ)[ﾟεﾟ]+';
            if ($code <= 127) {
                $text .= preg_replace_callback('/([0-7])/', function($match) use ($level) {
                    $byte = intval($match[1]);
                    return ($level ? self::randomize($byte, $level) : self::$bytes[$byte]) . '+';
                }, decoct($code));
            }
            else {
                $hex = str_split(substr('000' . dechex($code), -4));
                $text .= "(oﾟｰﾟo)+ ";
                for ($i = 0, $len = count($hex); $i < $len; $i++) {
                    $text .= self::$bytes[hexdec($hex[$i])] . '+ ';
                }
            }
            $result .=  $text;

        }
        $result .= "(ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) ('_');";
        return $result;
    }

    /**
     * @var array
     */
    protected static $bytes = [
        "(c^_^o)",
        "(ﾟΘﾟ)",
        "((o^_^o) - (ﾟΘﾟ))",
        "(o^_^o)",
        "(ﾟｰﾟ)",
        "((ﾟｰﾟ) + (ﾟΘﾟ))",
        "((o^_^o) +(o^_^o))",
        "((ﾟｰﾟ) + (o^_^o))",
        "((ﾟｰﾟ) + (ﾟｰﾟ))",
        "((ﾟｰﾟ) + (ﾟｰﾟ) + (ﾟΘﾟ))",
        "(ﾟДﾟ) .ﾟωﾟﾉ",
        "(ﾟДﾟ) .ﾟΘﾟﾉ",
        "(ﾟДﾟ) ['c']",
        "(ﾟДﾟ) .ﾟｰﾟﾉ",
        "(ﾟДﾟ) .ﾟДﾟﾉ",
        "(ﾟДﾟ) [ﾟΘﾟ]",
    ];

    /**
     * @param int $byte
     * @param int $level
     * @return string
     */
    protected static function randomize($byte, $level)
    {
        $random = [
            0 => [['+0', '-0'], ['+1', '-1'], ['+3', '-3'], ['+4', '-4']],
            1 => [['+1', '-0'], ['+3', '-1', '-1'], ['+4', '-3']],
            2 => [['+3', '-1'], ['+4', '-3', '+1'], ['+3', '+3', '-4']],
            3 => [['+3', '-0'], ['+4', '-3', '+1', '+1']],
            4 => [['+4', '+0'], ['+1', '+3'], ['+4', '-0']],
            5 => [['+3', '+1', '+1'], ['+4', '+1'], ['+3', '+3', '-1']],
            6 => [['+3', '+3'], ['+4', '+1', '+1'], ['+4', '+3', '-1']],
            7 => [['+3', '+4'], ['+3', '+3', '+1'], ['+4', '+4', '-1']],
        ];
        while ($level--) {
            $byte = preg_replace_callback('/[0-7]/', function($match) use ($random) {
                $numbers = $random[$match[0]][mt_rand(0, count($random[$match[0]]) - 1)];
                shuffle($numbers);
                $byte = ltrim(implode('', $numbers), '+');
                return "($byte)";
            }, $byte);
        }
        $byte = str_replace('+-', '-', $byte);
        return str_replace(array_keys(self::$bytes), self::$bytes, $byte);
    }
}

echo AAEncoder::encode('hello');

**Comment by Kabinjp** [comment]
```
<?php
/**
 * Class AAEncoder
 * @author Andrey Izman <izmanw@gmail.com>
 * @link https://github.com/mervick/php-aaencoder
 * @license MIT
 */

/**
 * Class AAEncoder
 */
class AAEncoder
{
    /**
     * Encode any JavaScript program to Japanese style emoticons (^_^)
     * @param string $js
     * @param int $level [optional]
     * @return string
     */
    public static function encode($js, $level=0)
    {
        $result = "ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ ['_']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); " .
            "(ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);" .
            "(ﾟДﾟ)={ﾟΘﾟ: '_' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +'_') [ﾟΘﾟ] " .
            ",ﾟｰﾟﾉ :(ﾟωﾟﾉ+ '_')[o^_^o -(ﾟΘﾟ)] " .
            ",ﾟДﾟﾉ:((ﾟｰﾟ==3) +'_')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +'_') [c^_^o];" .
            "(ﾟДﾟ) ['c'] = ((ﾟДﾟ)+'_') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];" .
            "(ﾟДﾟ) ['o'] = ((ﾟДﾟ)+'_') [ﾟΘﾟ];" .
            "(ﾟoﾟ)=(ﾟДﾟ) ['c']+(ﾟДﾟ) ['o']+(ﾟωﾟﾉ +'_')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +'_') [ﾟｰﾟ] + " .
            "((ﾟДﾟ) +'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+" .
            "((ﾟｰﾟ==3) +'_') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) ['c']+" .
            "((ﾟДﾟ)+'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) ['o']+" .
            "((ﾟｰﾟ==3) +'_') [ﾟΘﾟ];(ﾟДﾟ) ['_'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];" .
            "(ﾟεﾟ)=((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+" .
            "((ﾟДﾟ)+'_') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +'_') [o^_^o -ﾟΘﾟ]+" .
            "((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟωﾟﾉ +'_') [ﾟΘﾟ]; " .
            "(ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]='\\\\'; " .
            "(ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];" .
            "(oﾟｰﾟo)=(ﾟωﾟﾉ +'_')[c^_^o];" .
            "(ﾟДﾟ) [ﾟoﾟ]='\\\"';" .
            "(ﾟДﾟ) ['_'] ( (ﾟДﾟ) ['_'] (ﾟεﾟ+" .
            "/*´∇｀*/(ﾟДﾟ)[ﾟoﾟ]+ ";

        for ($i = 0, $len = mb_strlen($js); $i < $len; $i++) {
            $code = unpack('N', mb_convert_encoding(mb_substr($js, $i, 1, 'UTF-8'), 'UCS-4BE', 'UTF-8'))[1];
            $text = '(ﾟДﾟ)[ﾟεﾟ]+';
            if ($code <= 127) {
                $text .= preg_replace_callback('/([0-7])/', function($match) use ($level) {
                    $byte = intval($match[1]);
                    return ($level ? self::randomize($byte, $level) : self::$bytes[$byte]) . '+';
                }, decoct($code));
            }
            else {
                $hex = str_split(substr('000' . dechex($code), -4));
                $text .= "(oﾟｰﾟo)+ ";
                for ($i = 0, $len = count($hex); $i < $len; $i++) {
                    $text .= self::$bytes[hexdec($hex[$i])] . '+ ';
                }
            }
            $result .=  $text;

        }
        $result .= "(ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) ('_');";
        return $result;
    }

    /**
     * @var array
     */
    protected static $bytes = [
        "(c^_^o)",
        "(ﾟΘﾟ)",
        "((o^_^o) - (ﾟΘﾟ))",
        "(o^_^o)",
        "(ﾟｰﾟ)",
        "((ﾟｰﾟ) + (ﾟΘﾟ))",
        "((o^_^o) +(o^_^o))",
        "((ﾟｰﾟ) + (o^_^o))",
        "((ﾟｰﾟ) + (ﾟｰﾟ))",
        "((ﾟｰﾟ) + (ﾟｰﾟ) + (ﾟΘﾟ))",
        "(ﾟДﾟ) .ﾟωﾟﾉ",
        "(ﾟДﾟ) .ﾟΘﾟﾉ",
        "(ﾟДﾟ) ['c']",
        "(ﾟДﾟ) .ﾟｰﾟﾉ",
        "(ﾟДﾟ) .ﾟДﾟﾉ",
        "(ﾟДﾟ) [ﾟΘﾟ]",
    ];

    /**
     * @param int $byte
     * @param int $level
     * @return string
     */
    protected static function randomize($byte, $level)
    {
        $random = [
            0 => [['+0', '-0'], ['+1', '-1'], ['+3', '-3'], ['+4', '-4']],
            1 => [['+1', '-0'], ['+3', '-1', '-1'], ['+4', '-3']],
            2 => [['+3', '-1'], ['+4', '-3', '+1'], ['+3', '+3', '-4']],
            3 => [['+3', '-0'], ['+4', '-3', '+1', '+1']],
            4 => [['+4', '+0'], ['+1', '+3'], ['+4', '-0']],
            5 => [['+3', '+1', '+1'], ['+4', '+1'], ['+3', '+3', '-1']],
            6 => [['+3', '+3'], ['+4', '+1', '+1'], ['+4', '+3', '-1']],
            7 => [['+3', '+4'], ['+3', '+3', '+1'], ['+4', '+4', '-1']],
        ];
        while ($level--) {
            $byte = preg_replace_callback('/[0-7]/', function($match) use ($random) {
                $numbers = $random[$match[0]][mt_rand(0, count($random[$match[0]]) - 1)];
                shuffle($numbers);
                $byte = ltrim(implode('', $numbers), '+');
                return "($byte)";
            }, $byte);
        }
        $byte = str_replace('+-', '-', $byte);
        return str_replace(array_keys(self::$bytes), self::$bytes, $byte);
    }
}

echo AAEncoder::encode('hello');
```

**Comment by Kabinjp** [comment]
I do not use cpanel, I use nginx + php-fpm
[https://rabuhoteru.asia/prueba.php](url)

**Comment by mervick** [comment]
working as expected,

```
/tmp $ git clone https://github.com/mervick/php-aaencoder
Cloning into 'php-aaencoder'...
remote: Counting objects: 46, done.
remote: Total 46 (delta 0), reused 0 (delta 0), pack-reused 46
Unpacking objects: 100% (46/46), done.

/tmp $ nano test.php
<?php
require __DIR__ . '/php-aaencoder/AADecoder.php';
require __DIR__ . '/php-aaencoder/AAEncoder.php';

echo AAEncoder::encode('hello'), PHP_EOL;
echo AADecoder::decode(AAEncoder::encode('hello 123')), PHP_EOL;

/tmp $ php7.2 -v
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

/tmp $ php7.2 test.php
ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ ['_']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: '_' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +'_') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ '_')
[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +'_')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +'_') [c^_^o];(ﾟДﾟ) ['c'] = ((ﾟДﾟ)+'_') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) ['o'] = ((ﾟДﾟ)+'_') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) ['c']+(ﾟДﾟ)
 ['o']+(ﾟωﾟﾉ +'_')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +'_') [ﾟｰﾟ] + ((ﾟДﾟ) +'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+((ﾟｰﾟ==3) +'_') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) ['c']+((ﾟДﾟ)+'_') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) ['o']+((ﾟ
ｰﾟ==3) +'_') [ﾟΘﾟ];(ﾟДﾟ) ['_'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+'_') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +'_') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +'_') [ﾟΘﾟ]+ (ﾟωﾟﾉ
 +'_') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]='\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +'_')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]='\"';(ﾟДﾟ) ['_'] ( (ﾟДﾟ) ['_'] (ﾟεﾟ+/*´∇｀*/(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟ
εﾟ]+(ﾟΘﾟ)+((ﾟｰﾟ) + (ﾟΘﾟ))+(c^_^o)+(ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+(ﾟｰﾟ)+((ﾟｰﾟ) + (ﾟΘﾟ))+(ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+((ﾟｰﾟ) + (ﾟΘﾟ))+(ﾟｰﾟ)+(ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+((ﾟｰﾟ) + (ﾟΘﾟ))+(ﾟｰﾟ)+(ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+
((ﾟｰﾟ) + (ﾟΘﾟ))+((ﾟｰﾟ) + (o^_^o))+(ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) ('_');
hello 123;

```

**Comment by mervick** [comment]
If you use it in browser, looks like you have wrong encoding of html, it must be utf-8

**Comment by Kabinjp** [comment]
I have the UTF-8 active in the php.ini, it does not show it as it should be

**Comment by Kabinjp** [comment]
PHP 7.2.4 (cli) (built: Mar 27 2018 17:23:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.0, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.4, Copyright (c) 1999-2018, by Zend Technologies

**Comment by mervick** [comment]
> I have the UTF-8 active in the php.ini, it does not show it as it should be

in browser you should add utf-8 encoding at head
```html
<head>
  <meta charset="UTF-8">
</head>
```

**Comment by Kabinjp** [comment]
thanks, I already managed to solve the problem, it was the coding of the php file
